### ISSUE TITLE
Server has been down for several days "for maintenance"

### ISSUE THREAD

**Issue by hickst** [nipreps/mriqcwebapi#49]
Hi all,

Could you please tell us when the MRIQC web API will be available again? Thanks.

**Comment by hickst** [comment]
@rwblair Sorry to bug you again but is the MRIQC web API server down for a reason or just crashed? Any idea when will it be available again?

**Comment by rwblair** [comment]
@hickst sorry I missed  your first message. Certainly an unplanned outage, looking into it now.

**Comment by rwblair** [comment]
Should be back up now, let me know if you have any issues with it.

**Comment by hickst** [comment]
@rwblair It looks like it's working now. Thanks!

**Comment by hickst** [comment]
@rwblair Oops...looks like the web API server is down again today.

**Comment by rwblair** [comment]
Going through the logs it looks like docker was being restarted by systemd after upgrades but nginx failed to restart because the swagger container wasn't up. The swagger container was not set to restart automatically, so I enabled that. Hopefully that will allow it to come up when the docker daemon gets bounced and prevent this from happening.

**Comment by hickst** [comment]
@rwblair Yea, sometimes getting dependent containers to synchronize on startup can be a real pain. Thanks for getting it working again!
